name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Позволяет запускать workflow вручную через GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 4836297/postgres-application:$GITHUB_RUN_NUMBER

    - name: Push The Docker image into Docker Hub
      run: docker push 4836297/postgres-application:$GITHUB_RUN_NUMBER

    - name: Say Hello
      run: echo "Hello, $GITHUB_ACTOR!"

    - name: Check version
      run: echo "Docker image version is 4836297/postgres-application:$GITHUB_RUN_NUMBER"  

  update-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Clone Target Repo
      run: |
        git clone https://github.com/Artyom996/manif.git target-repo
        cd target-repo
        git checkout master

    - name: Update values.yaml
      run: |
        pwd
        ls -la
        cd target-repo
        TAG="$GITHUB_RUN_NUMBER"
        echo "Updating values.yaml with tag: $TAG"
        sed -i "s/tag: .*/tag: $TAG/" application/values.yaml

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        cd target-repo
        git add application/values.yaml
        git commit -m "Update Docker image tag to $GITHUB_RUN_NUMBER"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
