name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 4836297/postgres-application:$GITHUB_RUN_NUMBER

    - name: Push The Docker image into Docker Hub
      run: docker push 4836297/postgres-application:$GITHUB_RUN_NUMBER

    - name: Say Hello
      run: echo "Hello, $GITHUB_ACTOR!"

  manual-approval:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
    - name: Manual Approval
      run: echo "Manual approval required to continue."
      env:
        APPROVAL: ${{ secrets.APPROVAL }}
      if: env.APPROVAL != 'yes'

    - name: Run Custom Bash Script
      run: |
        echo "Running the manual script!"
        ./deploy.sh
      if: env.APPROVAL == 'yes'
